{
	"$schema": "node_modules/wrangler/config-schema.json",
	"name": "boltdiy3",
	"main": "./src/worker/index.ts",
	"compatibility_date": "2024-02-09",
	"compatibility_flags": ["nodejs_compat"],
	"observability": {
		"enabled": true
	},
	"upload_source_maps": true,
	"assets": {
		"directory": "./dist/client",
	
	}
}
