{
	"name": "boltdiy4",
	"compatibility_date": "2024-02-09",
	"compatibility_flags": ["nodejs_compat"],
	"observability": {"enabled": true	},
	pages_build_output_dir = "./build/client",
send_metrics = false
}
